services:
  nginx:
    image: butler/nginx
    container_name: butler-nginx-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8443:443"
    volumes:
    - ../../:/usr/src/app
    - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - butler-network

networks:
  butler-network:
    driver: bridge